"""Command-line interface: ``faceswap-video`` / ``python -m faceswap_video``."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from . import models
from .engine import MODES
from .label import DEFAULT_LABEL

CONSENT_TEXT = (
    "Only swap faces of people who have agreed to it. Output is labelled as "
    "AI-generated by default; keep that label when sharing."
)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="faceswap-video",
        description="Replace faces in a video with the face from a source image.",
        epilog=CONSENT_TEXT,
    )
    p.add_argument("-s", "--source", type=Path, help="image containing the face to insert")
    p.add_argument("-t", "--target", type=Path, help="video to modify")
    p.add_argument("-o", "--output", type=Path, help="output .mp4 path")
    p.add_argument("--mode", choices=MODES, default="all",
                   help="which faces to replace (default: all)")
    p.add_argument("--reference", type=Path,
                   help="image of the person to replace (for --mode reference)")
    p.add_argument("--threshold", type=float, default=0.35,
                   help="cosine similarity cutoff for --mode reference (default: 0.35)")
    p.add_argument("--label-text", default=DEFAULT_LABEL,
                   help="text of the visible AI-generated label")
    p.add_argument("--no-label", action="store_true",
                   help="omit the visible label (metadata tag is still written)")
    p.add_argument("--max-frames", type=int, help="stop after N frames (for quick previews)")
    p.add_argument("--crf", type=int, default=18, help="x264 quality, lower is better (default: 18)")
    p.add_argument("--det-size", type=int, default=640, help="face detector input size")
    p.add_argument("--providers", nargs="+",
                   help="ONNX Runtime providers, e.g. CUDAExecutionProvider CPUExecutionProvider")
    p.add_argument("--model-dir", type=Path,
                   help="model directory (default: $FACESWAP_MODEL_DIR or ~/.insightface)")
    p.add_argument("--offline", action="store_true", help="never download models")
    p.add_argument("--download-models", action="store_true", help="fetch models and exit")
    p.add_argument("--consent", action="store_true",
                   help="confirm everyone whose face is used or replaced has consented")
    return p


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.download_models:
        from .engine import FaceSwapper

        FaceSwapper(args.model_dir, args.providers)
        print(f"Models ready in {args.model_dir or models.default_model_root()}")
        return 0

    missing = [f"--{n}" for n in ("source", "target", "output") if getattr(args, n) is None]
    if missing:
        parser.error("the following arguments are required: " + ", ".join(missing))
    if args.mode == "reference" and args.reference is None:
        parser.error("--mode reference needs --reference")
    if not args.consent:
        parser.error("pass --consent to confirm you have permission. " + CONSENT_TEXT)
    for path in (args.source, args.target, args.reference):
        if path is not None and not path.exists():
            parser.error(f"file not found: {path}")

    from .engine import FaceSwapper, NoFaceError
    from .pipeline import SwapJob, run

    def progress(done: int, total: int) -> None:
        if done % 10 == 0 or done == total:
            msg = f"{done}/{total}" if total else str(done)
            print(f"\rframes {msg}", end="", file=sys.stderr, flush=True)

    job = SwapJob(
        source_image=args.source,
        target_video=args.target,
        output=args.output,
        mode=args.mode,
        reference_image=args.reference,
        threshold=args.threshold,
        label=None if args.no_label else args.label_text,
        max_frames=args.max_frames,
        crf=args.crf,
    )
    try:
        swapper = FaceSwapper(args.model_dir, args.providers, args.det_size, not args.offline)
        stats = run(job, swapper, progress)
    except (NoFaceError, FileNotFoundError, ValueError, RuntimeError) as exc:
        print(f"\nerror: {exc}", file=sys.stderr)
        return 1
    print(
        f"\nWrote {args.output}: {stats.frames} frames, "
        f"{stats.faces_swapped} faces swapped in {stats.frames_with_swap} frames.",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
